### ISSUE TITLE
Test suite fails to be run from out-of-source directory

### ISSUE THREAD

**Issue by laods** [CRAVA/crava#12]
Hi CRAVA developers!

I am currently testing CRAVA on Statoil's workstations (RH5 and RH6). I have succesfully built CRAVA on both, but are encountering some problems with running the test suite. According to the README file it should be possible to run the test suite from the test directory itself:

```
How to use the test suite:
--------------------------

1) From directory above  : make test
2) From current directory: ./TestScript.pl path-to-executable/cravarun
```

This is a nice feature as we don't have to copy the test suite directory (which is quite large) to all build realizations. However, when I call `./TestScript.pl path-to-executable/cravarun`, I get the following error message:

```
Cannot open dir '../src': No such file or directory
Cannot open dir '../libs/lib': No such file or directory
Cannot open dir '../libs/boost': No such file or directory
Cannot open dir '../findgrammar': No such file or directory
Cannot open dir '../libs/nrlib/eclipsegrid': No such file or directory
...
```

It seems like `./TestScript.pl` assumes that its parent directory is the source directory. 

* Should it be possible to run the test suite out-of-source?
* If yes; Why does it fail for me?
* If no; Is it possible to implement this feature? (This will save some memory)

@ulvmoen 
The build failure reported by Hudson/Jenkins on your e-mail was caused by this as I had to copy the test suite directory to the `/tmp` directory where the building takes place. This caused the error 'No space left on device'.

**Comment by alfbr** [comment]
Seems this one is solved, closing. Please reopen if you believe there are still issues.
