### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by spj2000** [CRAVA/crava#207]
hi,
I tried installing CRAVA on cygwin, with ATLAS. But realised I need GNU/Linux. what distribution should I use ? any suggestions are welcome.
Thanks,
spj2000

**Comment by alfbr** [comment]
It compiles on just about any linux distribution. Make sure you have Atlas development libraries installed before you run make as the readme file suggests. I have tested on Red Hat, Ubunu and Debian.

**Comment by pdahle** [comment]
If you've got Visual Studio available, you can also use
Windows. The project files you need are included in
the project.

Best regards
Pål

**Comment by spj2000** [comment]
Thanks. I was able to build using Visual studio 2010 and MKL libraries. There were a bunch of warnings, but no errors.  I do not have test suite or data. Is there a way I can get those, to try the crava.exe ?

**Comment by pdahle** [comment]
On 07/29/2015 10:33 PM, spj2000 wrote:
> Thanks. I was able to build using Visual studio 2010 and MKL libraries.
> There were a bunch of warnings, but no errors. I do not have test suite
> or data. Is there a way I can get those, to try the crava.exe ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CRAVA/crava/issues/207#issuecomment-126087222>.


No, unfortunately, all data is restricted.

I guess we should do something about that so that people
get a chance to verify the executable.

Best regards
Pål

**Comment by alfbr** [comment]
Unfortunately freeing datasets and creating tutorials are typically resource consuming tasks. I am not aware of any effort to provide it. Maybe you want to share your interest in Crava, and what you would like to accomplish? Feel free to pop a mail to either of us if you prefer sharing in private.

**Comment by alfbr** [comment]
Installation issues seems fixed, and no response. Closing.
