### ISSUE TITLE
BUG: default-Resampling of "Number of layers"

### ISSUE THREAD

**Issue by tinaek** [CRAVA/crava#214]
Horizon-tab:
- <Number of layers>
If "Number of Layers" are not set in first run (run 1), Crava makes its own number (302), dependent of the Correlation direction ==> OK!
BUT:
When rerunning the Crava (run 2) with the same "number of layers" (302) as Crava gave in the first run (run 1), the "number of layers" are being resampled ( to 318) due to correlation direction....but the surface direction has not been changed in run 2 compared to run 1.
Shouldn't the "number of layers" then be kept the same in run 2 as it was "defaulted by Crava" in run 1?
Ex:

****************************************************************************************************
*****                            Setting up multiple interval grid                             ***** (taken from logfile)
****************************************************************************************************
RUN 1: Creating extended simbox with one correlation surface for interval 'zone 1'.
          Z padding sizes estimated from an assumed wavelet length for interval 'zone 1':
          zPad, zPadFac, nz, nzPad                 :   200ms, 0.192,  **302**,  360

Run 2:Creating extended simbox with one correlation surface for interval 'zone 1'.
          Number of layers in interval zone 1 increased from **302** to **318** because of the correlation direction.
         Z padding sizes estimated from an assumed wavelet length for interval 'zone 1':
        zPad, zPadFac, nz, nzPad                 :   200ms, 0.179,   **318**,  375

**Comment by hgolsen** [comment]
CRA-820

**Comment by alfbr** [comment]
Make clear difference between number of layers in inversion grid and visualization grid.

**Comment by hgolsen** [comment]
The logging information regarding the different grids are updated. We emphasize that the simbox used for inversion is temporary, and added more logging regarding the final visualization grid.

**Comment by alfbr** [comment]
Thanks!
