### ISSUE TITLE
Survey Information: Wavelet and noise estimation interval: Top/Base surface

### ISSUE THREAD

**Issue by tinaek** [CRAVA/crava#217]
These interval inputs: Top and Base (time) surfaces should be able to read text/ASCII.files, or constant values.
Ex: 
Time Top Surface (ms): 1500 / or / Top_Horizon.txt
Time Base Surface (ms): 3000 / or / Base_Horizon.txt

Per today they are only able to read STORM.files.

**Comment by hgolsen** [comment]
Issue now ok. We have added support for ascii files and constant values for wavelet intervals.

**Comment by alfbr** [comment]
Great, thanks!
