### ISSUE TITLE
Horizons: Top/Base Surface files in text, ascii, dat etc.

### ISSUE THREAD

**Issue by tinaek** [CRAVA/crava#218]
The interval input files: Top and Base (time) surfaces should be able to read text/ASCII/DAT.files:
Ex: 
zone1: Top_Horizon.txt / or / Top_Horizon.dat
zone2: BCU.txt
zone3: Base_Horizon.txt

Per today they are only able to read STORM.files and constant values.

**Comment by hgolsen** [comment]
Last year we added  the support for multicolumn ascii files (text files with five columns, x,y,z IL, XL). Are you using the lastest version? Or is this something else?

**Comment by tinaek** [comment]
Using the latest version. Crava 4.0

**Comment by hgolsen** [comment]
This is ok, was related to #228.
