### ISSUE TITLE
Wavelet fixes

### ISSUE THREAD

**Issue by alfbr** [CRAVA/crava#219]
Wavelet estimate scale by default CRA-788
Wavelet in the logfile, gain should have a more intuitive name, e.g., scale CRA-792
Wavelet Present the scaling in a more comprehensive way CRA-792

**Comment by alfbr** [comment]
Default scale provided by GUI?

**Comment by RagnarHauge** [comment]
Total scaling is now reported.

**Comment by hgolsen** [comment]
This is checked in.

**Comment by alfbr** [comment]
Thanks you!
