### ISSUE TITLE
Bring manuals up to date

### ISSUE THREAD

**Issue by alfbr** [CRAVA/crava#225]
Ensure that deprecated tags are removed, while new or changed tags have up-to-date information. Bring version numbering into sync with CRAVA.

**Comment by alfbr** [comment]
Remove reference manual as it is no longer updated, and bring the user manual up-to-date.

**Comment by hgolsen** [comment]
https://jira.nr.no/browse/CRA-822

**Comment by alfbr** [comment]
Any update here?

**Comment by hgolsen** [comment]
Manuals are updated. We have removed the old reference manual and old/unused tags. There is also added surface description and a multizone inversion chapter.

**Comment by alfbr** [comment]
Thanks!
