### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by alfbr** [CRAVA/crava#226]
Especially in relation to the multizone inversion, there are opaque error messages that leaves the user clueless. Error messages should specify (if applicable) zone, well, data type and specific description of the problem. Ideally, a hint towards how to solve the problem should be provided too.

**Comment by hgolsen** [comment]
[CRA-825](https://jira.nr.no/browse/CRA-825)
While this is open-ended, there have been several updates regarding logging throughout this project.
