### ISSUE TITLE
Problem with compaction correlation structure

### ISSUE THREAD

**Issue by alfbr** [CRAVA/crava#227]
Seems like a bug, with frequent crashes. Harald can provide input and data set for reproduction.

**Comment by hflesche** [comment]
[background_base_conform.pptx](https://github.com/CRAVA/crava/files/167106/background_base_conform.pptx)
This files illustrates the sharp lateral changes that can come when base or top conform correlation structures are used to create background models. A proportional model would be preferrable, but as discussed there can be limitations in the FFT.

**Comment by hgolsen** [comment]
https://jira.nr.no/browse/CRA-837

**Comment by alfbr** [comment]
What is the status here?

**Comment by hgolsen** [comment]
Ragnar has started looking at this issue. There was some missing data. We received those today.

**Comment by alfbr** [comment]
Any update on this?

**Comment by RagnarHauge** [comment]
Problems were related to resampling issues and trying to write SegY files with very thin cells in the original grid. A fix for this has been implemented, and waits for code review by Håvard in a pull request.

**Comment by hgolsen** [comment]
The fix is checked in now.

**Comment by RagnarHauge** [comment]
The undef problems observed in this case does not relate to the compaction structure use, but is a separate bug due to lack of well data when trying to scale wavelet locally in a zone. Will create issue for it and fix it after next week.

**Comment by alfbr** [comment]
Great, thanks!
