### ISSUE TITLE
Problem with ASCII surfaces

### ISSUE THREAD

**Issue by alfbr** [CRAVA/crava#228]
We have a case where storm surfaces works fine, but ASCII surfaces fail. @tinaek can provide data set.

**Comment by alfbr** [comment]
Issue #218 ?

**Comment by alfbr** [comment]
Issue #217 ?

**Comment by hgolsen** [comment]
Hi. We can now start to look at this bug. Can you upload the data set to the NR ftp server?

**Comment by alfbr** [comment]
xml-file, log file and the ASCII input files have been uploaded. Tried to upload the input folder directly, but that did not work for recursively, so please delete that folder. You will find the folder with content in a zip-file. Please tell us what else you need from the input. Note the this set-up works with RMS horizons, the same surfaces in ASCII format failed.

**Comment by hgolsen** [comment]
Thanks. The first thing I can see is that the file 'constant1500.txt' is not the proper ascii-format. Crava requires the file to have 5 columns (X, Y, Z, IL and XL), each with a header. This file only has three columns and no header.
The (current) error message 'Did not recognize file as a multicolumns ascii file' is not very constructive..

**Comment by alfbr** [comment]
What is the status here?

**Comment by hgolsen** [comment]
This is fixed.

**Comment by alfbr** [comment]
Thanks!
