### ISSUE TITLE
Segy cube from HampsonRussel fail to import

### ISSUE THREAD

**Issue by alfbr** [CRAVA/crava#229]
Same cube exported from OpenWorks loads fine. Seems to be wrongly detected header information at fault. Cube already transferred.

**Comment by hgolsen** [comment]
CRA-821

**Comment by alfbr** [comment]
Consider removing header check for segy all together.

**Comment by hgolsen** [comment]
We have added that if a Crava can't recognize the file-type for seismic, it will try to read it as SegY (but with a warning).

However, when trying to read the cube above (Near15_RP14.sgy) we get the following error in Crava:
"In trace number 0: Different sampling densities given. Initial sampling density of 4ms changed to 5 in trace with XL 2500 and IL 1500."

Looks like the 4ms is taken from the BinaryHeader and the 5ms from the TraceHeader. Does this sound familiar given the current segy-file? And is this the kind of check you suggest we should consider to remove?

**Comment by RainerTonn** [comment]
I suspect there is a HRS issue. The original file was a 5m sampled PSDM which I converted to a 4ms time sampled time version. With the contradiction in the header information it is hard to decide what is correct. However, CRAVA is supposed to be run on time seismic. Therefore I suggest:
If CRAVA encounters a sampling problem it should pops up with a warning asking the user if the input is time. If the input is time, only sampling rates like 1ms, 2ms and 4ms should be accepted and if this SR is in the binary header it should be accepted.

**Comment by alfbr** [comment]
There are good arguments either way, I do end up supporting Rainer's suggestion though. Mainly because other seismic packages will read in this cube fine. Users will typically respond negatively is CRAVA is more strict than competing solutions. A clear warning message is certainly needed though.

**Comment by hgolsen** [comment]
Ok, we will then change Crava to allow SegY cubes with sampling rates of 1, 2 or 4 ms in BinaryHead. If there are inconsistencies we will give a warning and add the issue to the task list.

**Comment by alfbr** [comment]
This is confirmed fixed, thank you!
