### ISSUE TITLE
Failing to read well logs

### ISSUE THREAD

**Issue by RainerTonn** [CRAVA/crava#240]
Hi, 
I have two Crava projects. One is running smoothly and the second one fails reading the log data (Capture.png)
Attached are the input files. Harpoon failed and Bay did load fine. 
I do not see any difference between the files. Do you have any advice on what went wrong?
![capture](https://cloud.githubusercontent.com/assets/19913195/17632817/f27ea0a6-60a4-11e6-9f25-087adbcee447.PNG)
[Harpoon_O-85_aug16.txt](https://github.com/CRAVA/crava/files/415957/Harpoon_O-85_aug16.txt)
[Bay_Du_Nord_C-78.txt](https://github.com/CRAVA/crava/files/415959/Bay_Du_Nord_C-78.txt)

**Comment by pdahle** [comment]
Hi Rainer.

Did you run your jobs with the highest logging level?

It's hard from the output to see what is wrong. I also recommend
you to download a new version of CRAVA and recompile. There has
been alot of minor fixes lately.

Best regards
Pål Dahle

**Comment by hgolsen** [comment]
Hello,

I tried to read your wells (added them in a different project), and both read without error.
But that was with Crava 4.0, and from the screenshot it looks like you are using an old version of Crava (3.0 / CRAVA_MONCO2-branch)?

**Comment by RainerTonn** [comment]
With the execution "cravaguidaily' I executed Carva V4. Also the logging reporting is set to the highest level.
The error message remains the same and the log file is attached.
Cheers,

Rainer
[Test1logFile.txt](https://github.com/CRAVA/crava/files/417874/Test1logFile.txt)

**Comment by hgolsen** [comment]
There are two main branches of Crava, "CRAVA_MONCO2" and "master".

The "master"-branch is the main branch and the one that contains the multizone-inversion. This is also the branch that we keep developing on (like the fixes we did before the summer).
The "CRAVA_MONCO2"-branch is a branch that hasn't received any development for the last two years, but it contains some functionality that the master-branch misses like 4D inversion and gravimetric-inversion.

I see however that both branches produces a "C R A V A  -  4.0.0 beta" in the logfile (I thought MONCO2 had a 3.0 label).

When we look at the logfile you sent, it looks like a logfile that is produced by the "CRAVA_MONCO2"-branch. Are you deliberately on this branch?

**Comment by RainerTonn** [comment]
No, 
I see three options to run crava:
- run cravagui >>> results in starting Crava 3
- run cravarundaily >>> does not start but returns: usage: cravarundaily modelfile (see attachment)
-run cravaguidaily >>> starts Crava 4 as shown above

![capture](https://cloud.githubusercontent.com/assets/19913195/17663414/f4f67236-62c6-11e6-87f9-45aa53b2e390.PNG)

**Comment by alfbr** [comment]
Thanks for all input, please hold until tomorrow. We will take a look at the case from here.

**Comment by alfbr** [comment]
Tested with latest version of CRAVA, it works!
