### ISSUE TITLE
Import of XYZ_Il_Xl horizons 

### ISSUE THREAD

**Issue by hflesche** [CRAVA/crava#260]
I haven't tested horizon import for format XYZIlXl in cases where the survey is not NS-EW oriented. I have such a case here, and the geometry of the inversion becomes all wrong. I compared the input and output surfaces in RMS, and as the ilustration shows they seem to be transposed, but in addition the time scale is also wrong. I have a hard time understanding this, as the format should be the same as that which was tested on OseEast last year.

**Comment by hgolsen** [comment]
We are checking in a fix for this now, see our test in the image below. 
Please verify once the pullrequest (#262) is merged.

![cra863_new_results](https://user-images.githubusercontent.com/4331152/27169111-c5d49d1c-51a8-11e7-9bdc-11883938e80b.png)

**Comment by hflesche** [comment]
Should have been closed long time ago - overlooked.
