### ISSUE TITLE
Compaction correlation for background model causes strange error message

### ISSUE THREAD

**Issue by utheune** [CRAVA/crava#275]
Hi,

I am running a CRAVA inversion for a Statoil field, where I am setting up a multi zone inversion, which contains 8 zones.
CRAVA runs smoothly through the inversion if I set the correlation structure to base correlation structure for all but the last zone. However, it maybe better for the data  if zone 3 (third from top) would use 'compaction correlation'. If I run CRAVA with setting, it stops when "blocking wells for correlation"  for the first zone, where I did not change anything. The error message is:
Interval: zone 1

There are no nonsynthetic Vs logs available. Corr(Vp,Vs) is set to 0.7 and Corr(Vs,Rho) is set to 0.
cravarundaily: ../libs/flens/fullstorage.tcc:869: T& flens::FullStorage<T, Order>::operator()(int, int) 
[with T = double, flens::StorageOrder Order = (flens::StorageOrder)1u]: Assertion `row>=_firstRow' failed.

It is correct that the Vs log is synthetic, but should not cause any problems here, I assume?"

Hope you can help!

Best regards,
uli

**Comment by hgolsen** [comment]
Hello,

It sounds weird that you get an error in zone1 only by changing certain settings in zone3.
Is it possible to send us the example (data and modelfile)? It would help to recreate this problem.

Regards,
Håvard

**Comment by utheune** [comment]
Hi Håvard,

Sure – I will upload the data soon. Is a tar archive the best way?

uli

**Comment by hgolsen** [comment]
Thanks. Yes, a tar archive is fine for us.

Regards,
Håvard

**Comment by utheune** [comment]
Will do so soon – I am struggling with the ftp server a bit at the moment.

Regards,
uli

**Comment by utheune** [comment]
Hi Håvard,

We tried now several times to ftp the file to NR’s ftp server but we always got automatically disconnected by the server (I do not remember the correct error message - sorry).
Could you maybe check if there are any problems on your side (full disk maybe)? The file we try to upload is about 900 MB large.

Best regards,
uli

**Comment by hgolsen** [comment]
Hello,

The FTP is not full, I also tested by uploaded a 2GB file to check and it went through.

There are two files on the server, ExampleUli.tar.gz and TestcaseUli.tar.gz, but they are only 30 MB and 70MB.
I can contact IT here, but then I would need the correct error message.

Alternatively, is there a Statoil FTP that we can use?

Regards,
Håvard

**Comment by utheune** [comment]
Hi,

computers & internet … don’t know why but now when I tried again to transfer the file (just to get the error message), the transfer succeeded.
You should now have a file called StatoilExample.tar.gz on your server. The other files are just fragments of our previous failed transfers.

During the transfer, a message popped up stating that the “Connection closed by server” but it it don’t interrupted the transfer.

Let me know if you have troubles reading the file or questions about its content.

Best regards,
uli

**Comment by hgolsen** [comment]
Hello.

That’s good to hear. I will unzip it and take a look at it.

Regards,
Håvard

**Comment by hgolsen** [comment]
Hello again,

A fix for this was checked in to Crava on github today. Your case now runs without any errors here.

Please test again the next time Crava is updated (should be nightly), and let us know if you still have any problems.

Regards,
Håvard

From: Håvard Goodwin Olsen
Sent: mandag 11. desember 2017 14:10
To: 'CRAVA/crava'; CRAVA/crava
Cc: Comment
Subject: RE: [CRAVA/crava] Compaction correlation for background model causes strange error message (#275)

Hello.

That’s good to hear. I will unzip it and take a look at it.

Regards,
Håvard

**Comment by utheune** [comment]
Hei Håvard,

Tested and it seems to work!
Thank you for your assistance in this matter.

Godt nytt år,
uli

**Comment by hgolsen** [comment]
Hello.

Godt nytt år.

Thats good to hear.
I will close this issue then.

Regards,
Håvard
