### ISSUE TITLE
wavelet length estimated too long

### ISSUE THREAD

**Issue by ganpan** [CRAVA/crava#47]
I have observed in some cases the CRAVA estimated too long wavelet than what we expected. The default wavelet length in CRAVA is 200ms. And the CRAVA estimated wavelet should usually be close to 200ms. But there are some cases CRAVA estimate wavelets which are as long as 2000ms. It will easily end to an abortion because there are usually no wells have such long continuous logs.

**Comment by alfbr** [comment]
I believe this issues is resolved, closing. Please re-open if issue still remains.
